-- Active: 1697802336085@@10.76.20.51@3306@SALDBD
/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 20-oct.-2023 08:48:53 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Category` CASCADE
;

DROP TABLE IF EXISTS `Order` CASCADE
;

DROP TABLE IF EXISTS `Product` CASCADE
;

DROP TABLE IF EXISTS `Productofferingprice` CASCADE
;

DROP TABLE IF EXISTS `Productorderitem` CASCADE
;

/* Create Tables */

CREATE TABLE `Category`
(
	`CategoryID` INT NOT NULL AUTO_INCREMENT,
	`Code` VARCHAR(50) NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`Validfor_startdatetime` DATETIME NULL,
	`Validfor_enddatetime` DATETIME NULL,
	CONSTRAINT `PK_Category` PRIMARY KEY (`CategoryID` ASC)
)

;

CREATE TABLE `Order`
(
	`OrderID` INT NOT NULL AUTO_INCREMENT,
	`Type` VARCHAR(15) NULL,
	`Status` TINYTEXT NOT NULL,
	`Creationdate` DATETIME(6) NOT NULL,
	`Lastupdate` DATETIME(6) NOT NULL,
	`Userupdate` VARCHAR(15) NULL,
	CONSTRAINT `PK_Order` PRIMARY KEY (`OrderID` ASC)
)

;

CREATE TABLE `Product`
(
	`ProductID` INT NOT NULL AUTO_INCREMENT,
	`Code` VARCHAR(50) NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`Description` VARCHAR(50) NULL,
	`CatalogtypeID` INT NOT NULL,
	`Status` TINYTEXT NULL,
	`Quantity` INT NULL,
	CONSTRAINT `PK_Product` PRIMARY KEY (`ProductID` ASC)
)

;

CREATE TABLE `Productofferingprice`
(
	`ProductofferingpricereforvalueID` INT NOT NULL AUTO_INCREMENT,
	`ProductorderitemID` INT NULL,
	`Code` VARCHAR(50) NULL,
	`Name` VARCHAR(50) NULL,
	`Price` DOUBLE(10,2) NULL,
	`Tax` DOUBLE(10,2) NULL,
	`Validfor_startdatetime` DATETIME NULL,
	`Validfor_enddatetime` DATETIME NULL,
	CONSTRAINT `PK_Productofferingpricereforvalue` PRIMARY KEY (`ProductofferingpricereforvalueID` ASC)
)

;

CREATE TABLE `Productorderitem`
(
	`ProductorderitemID` INT NOT NULL AUTO_INCREMENT,
	`OrderID` INT NOT NULL,
	`Status` TINYTEXT NULL,
	`Action` TINYTEXT NULL,
	`ProductID` INT NULL,
	CONSTRAINT `PK_Productorderitem` PRIMARY KEY (`ProductorderitemID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Product` 
 ADD CONSTRAINT `FK_Product_Category`
	FOREIGN KEY (`CatalogtypeID`) REFERENCES `Category` (`CategoryID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Productofferingprice` 
 ADD CONSTRAINT `FK_ProductOfferingPriceRefOrValue_offeringPrice`
	FOREIGN KEY (`ProductorderitemID`) REFERENCES `Productorderitem` (`ProductorderitemID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Productorderitem` 
 ADD CONSTRAINT `FK_Productorderitem_Product`
	FOREIGN KEY (`ProductID`) REFERENCES `Product` (`ProductID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Productorderitem` 
 ADD CONSTRAINT `FK_Productorderitem_Order`
	FOREIGN KEY (`OrderID`) REFERENCES `Order` (`OrderID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;
